services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: notebooklm-clone-postgres

    environment:
      POSTGRES_DB: notebooklm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5435:5432"

    volumes:
      - notebooklm_pg_data:/var/lib/postgresql/data
 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d notebooklm"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  notebooklm_pg_data: